api_login_check:
    path: /api/login_check
    controller: Symfony\Bundle\FrameworkBundle\Controller\SecurityController

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }